### ISSUE TITLE
Add ContributingGuidelines.md 

### ISSUE THREAD

**Issue by shanvijha30** [thestarsahil/Counsellor#14]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@thestarsahil Could you please assign this issue to me under GSSOC 23.
Thank you!

**Comment by thestarsahil** [comment]
@shanvijha30 I am thrilled to receive your project request!
Go ahead ! 

If you have any questions, feel free to contact me via email or Discord or reach out to our team of project mentors.

Thank you for your contribution and let's make this project a huge success!

**Comment by shanvijha30** [comment]
@thestarsahil Added PR [#44](https://github.com/thestarsahil/Counsellor/pull/44)
Please review it.
