### ISSUE TITLE
[DOCS]: adding badges to readme.md file

### ISSUE THREAD

**Issue by AmanSingh6574** [thestarsahil/Counsellor#15]
I can add badges to the readme.md file 
pls assign me this issue under GSSoC'23 label
@thestarsahil 

![image](https://github.com/thestarsahil/Counsellor/assets/113782984/c868aa0b-9fda-4110-b87b-be94d19d48f8)

**Comment by thestarsahil** [comment]
Great job assigning the issue to the user @AmanSingh6574 ! The badges in the readme.md file will be a valuable addition to the project. It will help showcase important information and achievements related to the project, making it more informative and visually appealing for visitors. Keep up the good work in managing the project and addressing user requests. If you have any questions or need further assistance, feel free to reach out. Happy coding!

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by omkarguravv** [comment]
@AmanSingh6574 Join discord group for further discussion with collaborators, project admin and mentors.
For joining the group:

- Go to the Gssoc'23 discord channel.
- Go to FORUM category.
- In PROJECTS-INTRO you will get the project listed.
- Join the project discord channel.

Also join the Slack Channel!!

**Comment by AmanSingh6574** [comment]
@thestarsahil  pls add level to the pr
