### ISSUE TITLE
updating the navigation bar and making hover effect to enhance the ui

### ISSUE THREAD

**Issue by mridulsaggi** [thestarsahil/Counsellor#21]
i am a gssoc contributor and would like to contribute to this project.
i would like to make the hover effect to enhance the ui and will make navigation bar look more preety.
![Screenshot (80)](https://github.com/thestarsahil/Counsellor/assets/91930535/0cd9cc99-eb6e-4fd9-a906-a1f44aabaf22)

**Comment by ravirt7911** [comment]
Hello @thestarsahil 
I can add really good hover effect which go with the color palette and change the UI so please assign this to me.
