### ISSUE TITLE
[Improvement] Typewriter Effect in the Main heading

### ISSUE THREAD

**Issue by Anshika-Jain02** [thestarsahil/Counsellor#55]
*We can add a typewriter effect in the main heading to give it a dynamic effect and improves overall visual appearance of the website*

**Please assign me this issue under Gssoc'23 @thestarsahil**

![Counsellor](https://github.com/thestarsahil/Counsellor/assets/104912087/b2779a0d-20ab-4ab6-b994-e26e032dbe20)

**Comment by thestarsahil** [comment]
@Anshika-Jain02 
Thank you for your interest in working on this issue. I appreciate your suggestion to add a typewriter effect to the main heading, which will enhance the visual appearance and create a dynamic effect on the website.

Having an open discussion will help ensure that we collectively agree on the best approach and implementation for this feature. It will also provide an opportunity for collaboration and gathering valuable feedback from the community.
Please initiate the discussion and provide the necessary details about your proposed typewriter effect. I'm looking forward to seeing the conversation unfold and collaborating with you on this exciting enhancement.

**Comment by Anshika-Jain02** [comment]
Thank you sir for considering my addition to your project. As you must have seen that when we open the main page of GitHub preceding the login page a typewriter effect comes. I want to add a similar typewriter effect in the heading "Still Confused with College Choice" using the javascript setTimeout feature and then it creates an appearance as someone is typing the text in real time.

**Comment by Anshika-Jain02** [comment]
@thestarsahil can i start working on this?

**Comment by thestarsahil** [comment]
> @thestarsahil can i start working on this?

Yes i already assigned you
