### ISSUE TITLE
Well Organised README.md

### ISSUE THREAD

**Issue by thestarsahil** [thestarsahil/Counsellor#74]
**Bug Description:**
The current README.md file requires improvement.

**Steps to Reproduce:**
1. Read the existing README.md file.
2. Observe the areas that need improvement.

**Expected Behavior:**
The README.md file should provide clear and comprehensive information about the project.

**Proposed Changes:**
To improve the README.md file, the following changes are suggested:

1. Project Description: Provide a brief and concise description of the project, highlighting its purpose, goals, and any unique features.

2. Slack Channel Connection: Include a link to the Slack channel for easy access and collaboration. The link should be clickable and lead to the invitation page.
https://join.slack.com/t/counselllor/shared_invite/zt-1w7zos2td-lZBc_52HNvr8Jtvpt4gR5g

3. Developers Section: Create a section that outlines the different roles and responsibilities of developers working on the project. Mention separate repositories for web development, Android development, taxonomy editor, AI, and ML.

4. Working Team: List the different teams involved in the project, such as UI, frontend, backend, and server. Briefly describe the responsibilities of each team and their contributions to the project.

5. Contribution Guidelines: Provide clear instructions for contributing to the project. Include information on how developers can get involved, submit pull requests, and contribute to the codebase.

6. GirlScript Summer of Code 2023: Highlight the project's selection under GirlScript Summer of Code 2023. Explain the significance of this achievement and how it reflects the project's quality and potential.

By implementing these changes, the README.md file will become more informative, organized, and engaging, enabling users and potential contributors to better understand the project and get involved effectively.

Reference Organisation : 
https://github.com/openfoodfacts

**Comment by rohanmittal1163** [comment]
@thestarsahil can you assign this issue to me. I have read all the guidlines and i m sure that i can contribute in this under GSSOC'23

**Comment by ePSA-eJya** [comment]
i would want to work on this issue. i am a gssoc 23 contributor. please assign this issue to me @thestarsahil
